### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by Cal-Hagner** [Matt-Gleich/Morse#12]
- [x] Create `CONTRIBUTING.md`
- [x] Update `README.md` with supported applications
- [x] Create `docs` directory
- [x] Create instructions on creating soc-modules

**Comment by Cal-Hagner** [comment]
@Matt-Gleich Can you add issue templates? I don't have access to the repository settings.

**Comment by Matt-Gleich** [comment]
Don't you just put them in the `.github` folder? There isn't any setting in the settings.

**Comment by Cal-Hagner** [comment]
Nevermind, I found the button. Adding them directly is a legacy feature and not recommended.
